name = "Calculator"
uuid = "2624d050-e8cd-45c1-aac0-273a2a0ab6ce"
authors = ["akc14 <andrew.khoh@globalfoundries.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
